Update update-nr-dashbaord.yml

diff --git a/.github/workflows/update-nr-dashbaord.yml b/.github/workflows/update-nr-dashbaord.yml
--- a/.github/workflows/update-nr-dashbaord.yml
+++ b/.github/workflows/update-nr-dashbaord.yml
@@ -12,18 +12,20 @@ on:
       - 'release/**'
 
 jobs:
-  get_changed_endpoints_file_name:
+  get_changed_endpoints_info:
     runs-on: ubuntu-latest
     outputs:
-      fileName: ${{ steps.get-file-name.outputs.fileName }}
+      fileName: ${{ steps.get-changed-endpoints-info.outputs.fileName }}
+      releaseVersion: ${{ steps.get-changed-endpoints-info.outputs.releaseVersion }}
     steps:
-      - name: Get changed endpoint file name
-        id: get-file-name
+      - name: Get changed endpoints info
+        id: get-changed-endpoints-info
         run: |
           version=$(echo ${{ inputs.releaseBranch }} | grep -oP '[0-9]+\.[0-9]+\.[0-9]+')
           if [ -n "$version" ]; then
             echo "Release version is: $version"
             echo "File name is: Changed-Endpoints-$version.md"
+            echo "releaseVersion=$version" >> "GITHUB_OUTPUT"
             echo "fileName=Changed-Endpoints-$version.md" >> "$GITHUB_OUTPUT"
             cat 
           else
@@ -32,18 +34,75 @@ jobs:
           fi
   create_dashboard:
     runs-on: ubuntu-latest
-    needs: get_changed_endpoints_file_name
+    needs: get_changed_endpoints_info
     steps:
       - name: Get Release wiki
         uses: actions/checkout@v4
         with:
           repository: ${{github.repository}}.wiki
           sparse-checkout: |
-            ${{ needs.get_changed_endpoints_file_name.outputs.fileName }}
+            ${{ needs.get_changed_endpoints_info.outputs.fileName }}
           sparse-checkout-cone-mode: false
           path: wiki
       - name: Check file
         run: |
-          ls wiki
-          cat wiki/${{ needs.get_changed_endpoints_file_name.outputs.fileName }}
-       
+          file=${{ needs.get_changed_endpoints_info.outputs.fileName }}
+          if [ -f "$file" ]; then
+            echo "$file exists."
+          fi
+            echo "$file doesn't exist."
+            exit 1
+      - name: Get NR tools
+        uses: actions/checkout@v4
+        with:
+          repository: Pay-Baymax/bff-tools
+          path: tool
+      - name: Update dashboard config file
+        uses: actions/github-script@v6
+        with:
+          script: |
+            const fs = require('fs');
+            const readline = require('readline');
+            const fileName = `${{ needs.get_changed_endpoints_info.outputs.fileName }}`;
+            const version = `${{ needs.get_changed_endpoints_info.outputs.releaseVersion }}`;
+            
+            // Read the JSON file
+            let config;
+            fs.readFile('tool/new-relic/dashboard-generator/config/bff-release-ci.json', 'utf8', (err, data) => {
+              if (err) {
+                core.error('Error reading config file:', err);
+                core.setFailed(err);
+              }
+            
+              // Parse the JSON data
+              config = JSON.parse(data);
+            });
+            
+            // Set dashboard title
+            config.title = `BFF Release ${version} - Changed Endpoints`;
+            
+            // Set changed endpoints
+            let endpoints = config.endpoints;
+            endpoints.push(`"## ${version} APIs`)
+            fs.readFile(`wiki\${fileName}`, 'utf8', (err, data) => {
+              if (err) {
+                core.error('Error reading config file:', err);
+                core.setFailed(err);
+              }
+            
+              // Parse the JSON data
+              data.split(/\r?\n/).forEach(line => {
+                if(line.length > 0) {
+                  endpoints.push(line);
+                }});
+            });
+
+            // Write to file
+            fs.writeFile('tool/new-relic/dashboard-generator/config/bff-release-ci.json', JSON.stringify(config, null, 2), 'utf8', err => {
+              if (err) {
+                core.error('Error writing config file:', err);
+                core.setFailed(err);
+              }
+            });
+      - name: Check config file
+        run: cat tool/new-relic/dashboard-generator/config/bff-release-ci.json
